/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\public\\FishBowl.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FishBowl(props) {
  const { nodes, materials } = useGLTF('/FishBowl.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.99}>
        <mesh receiveShadow castShadow geometry={nodes.Sphere005.geometry} material={materials.Water} />
        <mesh receiveShadow castShadow geometry={nodes.Sphere005_1.geometry} material={materials['Material.005']} />
        <mesh receiveShadow castShadow geometry={nodes.Sphere005_2.geometry} material={materials.Sand} />
      </group>
    </group>
  )
}

useGLTF.preload('/FishBowl.glb')
