/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\public\\FishBowl.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshBasicMaterial, MeshPhysicalMaterial } from "three";

export function FishBowl(props) {
  const { nodes, materials } = useGLTF("/FishBowl.glb");

  const material = new MeshPhysicalMaterial({
    transparent: true,
    color: "rgba(0,0,0,0)",
    opacity: 0.1,
    ior: 1.5,
    roughness: 0,
    transmission: 1,
  });

  return (
    <group {...props} dispose={null}>
      <group scale={0.99}>
        <mesh
          receiveShadow
          geometry={nodes.Sphere005_1.geometry}
          material={material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Sphere005_2.geometry}
          material={materials.Sand}
        />
        <mesh
          receiveShadow
          geometry={nodes.Sphere005_3.geometry}
          material={materials["Water.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/FishBowl.glb");
