/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\public\\Table.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Table(props) {
  const { nodes, materials } = useGLTF('/Table.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, 1.15, 1.3]} rotation={[0, -0.7, 0]} scale={4.38}>
        <mesh receiveShadow castShadow geometry={nodes.Plane_1.geometry} material={materials.Cloth} />
        <mesh receiveShadow castShadow geometry={nodes.Plane_2.geometry} material={materials.WoodTable} />
      </group>
    </group>
  )
}

useGLTF.preload('/Table.glb')
